### ISSUE TITLE
Google Custom Search

### ISSUE THREAD

**Issue by Desno365** [mmistakes/so-simple-theme#114]
I'm trying to implement the Google Custom Search in my Jekyll website that uses the So Simple Theme.
It works, but it looks weird. A screenshot explains it better:

![screenshot](http://i.imgur.com/SXq0e9z.jpg)

This is the link of the page on my website so you can see it with your eyes. http://desno365.github.io/search/

It seems like one white line is above the GCS.

And finally this is the code that I'm using (I just copied and pasted the code that Google gave me):

```markdown
---
layout: page
title: Search through this website
excerpt: "Google Custom Search"
---

<gcse:search></gcse:search>


<script>
  (function() {
    var cx = '006106064300526171541:3996-ekg9iw';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
```

Does anyone know how to fix it?

**Comment by mmistakes** [comment]
You'll need to override the CSS Google is using to style their search box. Using the web developer tools in your browser of choice you can inspect the form elements and see what class names Google is using and adjust accordingly.

I quickly looked at it and seems like there are some heights being set on the input fields making them much smaller than what I use in the theme. That, and Google is using some messy looking markup to put the forms in a table which is conflicting with So Simple's base styles causing the lines. 

There's probably a blog post or two out there explaining how to best customize the search field. [Here's one](http://www.labnol.org/internet/google-custom-search-css/28360/) to get you started. 

You may be able to reset Google's style to make customizing it easier. I've never tried it but they offer some [guidance on how to turn it off](https://support.google.com/customsearch/answer/2631084?hl=en).

**Comment by Desno365** [comment]
Thanks for the suggestion, I'll try it.
If I find a fix I will post it here.
