### ISSUE TITLE
no excerpt: breaks search

### ISSUE THREAD

**Issue by wetty** [mmistakes/so-simple-theme#117]
If the excerpt: is not in the YAML front matter, the search will break, because the default page.excerpt ist surrounded with <p> and then the search did not show an result.

Currently I do not know how to get the default excerpt (first paragraph) without the html paragraph.

**Comment by wetty** [comment]
{{ page.excerpt | strip_html | strip_newlines }}
might help. But if there are some other formattings it will break again, as on my site.

**Comment by mmistakes** [comment]
Probably going to remove excerpts from search. It's way too fragile of a solution to guard against since everyone does their posts differently.

**Comment by mmistakes** [comment]
Fixed in 808c1043dfed9ee173bea9c740e5aa655407ff0a
