### ISSUE TITLE
{{site.url}} should be deprecated in favor or {{site.baseurl}}

### ISSUE THREAD

**Issue by sandeep** [mmistakes/so-simple-theme#120]
Changing from url to baseurl variable allows it to be overridden via the command line for local development. 
 
http://jekyllrb.com/docs/upgrading/ (see the bottom)

**Comment by mmistakes** [comment]
`{{ site.baseurl }}` and `{{ site.url }}` are two unique variables and both have their own use cases. In my experience baseurl is often misused or confused for url. If you want more background there's a [great post over here](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/) explaining why and when to use it (hint: it should be used only to mimic GitHub page's project folder structure in conjunction with {{ site.url }}).

If the goal is to override your site's url for easier local development that can still be done using `{{ site.url }}`. The way I do it is to have two config files, one for production and the other for local development. For my production I set `{{ site.url }}` to `url: https://domain.com` and for development `url: http://localhost:4000`.

When I work locally I start up Jekyll like so to load up my dev config file `jekyll serve --config _config-dev.yml`.

**Comment by sandeep** [comment]
ok go it. Thanks for the link!
