### ISSUE TITLE
Improve doc & scss file

### ISSUE THREAD

**Issue by cmoulliard** [mmistakes/so-simple-theme#129]
Hi Michael,

Is it possible to include more comments in the different sass files to explain : 
1) Which file has been modified and if it comes from an external source (+ version of the source) ?
Example: coderay, element, ...
2) I suppose that _site.scss is the main site scss file of this theme but it does not include a header with version(s), modifications & date of the modification ?
3) It could be interesting to mention in the header of the _scss file what is the css template file supposed to do : element, coderay, highlight, forms, ... & where they are used (page, post, ...) ?

**Comment by mmistakes** [comment]
All the Sass partials under `/_sass/vendor/` are styling for any scripts and such I didn't write (Magnific Popup, Font Awesome, Bourbon/Neat mixins, etc).

Everything else is my stuff. If I was to do it all over again I'd probably break things up more granular into components, but who has time for that :wink:

I'm generally not a fan of over documenting things, especially related to modification dates and versions. Git and GitHub exposes all that so I don't think my time is best spent dealing with that. There's opportunity to document some of the styling that isn't as obvious, but then again I'm not really building this as a framework for non-devs. Bootstrap and Foundation it's not.

**Comment by mmistakes** [comment]
And to be honest, I've moved on from most of these themes. I'm really only maintaining them to keep compatibility with current versions of Jekyll. I really don't have much free time to actively enhance and add new features to.

**Comment by cmoulliard** [comment]
Hi Michael,

As I will migrate to the latest version of "so-simple-them" & jekyllrb, I
will send you some PR based on my findings.
Regards,
Charles

On Tue, Mar 3, 2015 at 12:53 PM, Michael Rose <notifications@github.com>
wrote:

> And to be honest, I've moved on from most of these themes. I'm really only
> maintaining them to keep compatibility with current versions of Jekyll. I
> really don't have much free time to actively enhance and add new features
> to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmistakes/so-simple-theme/issues/129#issuecomment-76932161>
> .
>



-- 
Charles Moulliard
Apache Committer / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io
