### ISSUE TITLE
Introduce infinite scrolling for blogs.

### ISSUE THREAD

**Issue by Faiz7412** [mmistakes/so-simple-theme#134]
People don't like clicking on next or previous buttons to browse through more posts. Infinite scrolling is always good for authors and readers alike.

**Comment by Faiz7412** [comment]
Working on integrating this: https://github.com/infinite-scroll/infinite-scroll

**Comment by Faiz7412** [comment]
Working on integrating so-simple with this: https://github.com/infinite-scroll/infinite-scroll

**Comment by mmistakes** [comment]
Feel free to take a stab at this and submit a PR. I'm not a big fan of infinite scrolling blogs so it'll have to be something slick for me to merge in. 99.9% of the time they're done poorly and cause all kinds of UX problems (ie: they don't save your location in the scroll when hitting the back button).

**Comment by rafaelbiriba** [comment]
With a correct UX design to show that there is more content to load, the infinite scroll works great.
