### ISSUE TITLE
site-logo.png font

### ISSUE THREAD

**Issue by misterpark** [mmistakes/so-simple-theme#136]
Firstly, props to Michael for creating this theme. It's a marvellous thing – thanks for sharing.

Which font is used in the `site-logo.png` file? Is there a PSD file available for editing purposes?

I'd like to change the letters from `SO` to `MP` (my initials) on my blog: http://misterpark.co.uk.

Many thanks,

Mike

**Comment by mmistakes** [comment]
I'll have to see if I can dig up the PSD and add it to the project. To get you started the font is [Josefin Slab](https://www.google.com/fonts/specimen/Josefin+Slab).

**Comment by misterpark** [comment]
Thanks Michael.
