### ISSUE TITLE
Article vs. blog

### ISSUE THREAD

**Issue by misterpark** [mmistakes/so-simple-theme#137]
Silly question, but what is the difference between an article and a blog post? Thanks

**Comment by mmistakes** [comment]
Absolutely nothing. They're just examples of categories and how one could use them to break up content on the site and meant to be removed or adapted to fit your needs. The posts under "Articles" have `categories: articles` in the YAML Front Matter and "Blog" has `categories: blog`.

By setting a category in the YAML it will also add it the post's permalink... ie `domain.com/foo/post-name/index.html`. I also included sample index pages at [`articles/index.md`](https://github.com/mmistakes/so-simple-theme/blob/master/articles/index.md) and [`blog/index.md`](https://github.com/mmistakes/so-simple-theme/blob/master/blog/index.md) to show how you can display a list of posts limited by a specific category.

If you're only going to have blog posts on your site then you can ignore categories and just keep things simple.

**Comment by misterpark** [comment]
I suspected as much. Thanks for confirming.
