### ISSUE TITLE
Problems to add a youtube video

### ISSUE THREAD

**Issue by galeribcn** [mmistakes/so-simple-theme#138]
Hi!
I tray to add a video from youtube, bau its impossible. I follow the instruccions "add a space between the `<iframe>` tags and remove `allowfullscreen`. " but dont working...
What can I do? 
Thanks!
My email is erodsan@hotmail.com

**Comment by mmistakes** [comment]
What's not working? Video doesn't show up? It shows up wrong? Without some code to look at its hard to troubleshoot.

**Comment by galeribcn** [comment]
You're right! video doesn´tshow up...

<iframe width="576" height="432" src="
https://www.youtube.com/watch?v=cYb1w79GvqM" frameborder="0"> </iframe>

Thanks for your quick reply!
Eva

2015-03-27 15:20 GMT+01:00 Michael Rose <notifications@github.com>:

**Comment by mmistakes** [comment]
Ok. Do you have a GitHub repo with a link to the `_posts/xxxx-xx-post-title.md` file you're trying to place a video in?

You probably have some malformed Markdown in the file or perhaps your Jekyll setup is busted. If you run a fork of the So Simple repo locally does the [video in the sample post](https://mmistakes.github.io/so-simple-theme/articles/video-post/) show up? If it does then you definitely have an error in your personal repo.

Diff [my sample post](https://github.com/mmistakes/so-simple-theme/blob/master/_posts/articles/2013-06-25-video-post.md) with yours to spot any errors you might have made.

**Comment by mmistakes** [comment]
Closing.
