### ISSUE TITLE
Formspree contact form not working

### ISSUE THREAD

**Issue by ghost** [mmistakes/so-simple-theme#140]
I'm having difficulty implementing a [Formspree](http://formspree.io) contact form on [my website](http://misterpark.co.uk/contact). This is the [raw content of the page](https://raw.githubusercontent.com/misterpark/misterpark.github.io/master/contact/index.md). I heard about Formspree in [this blog post](http://sebastien.saunier.me/blog/2014/04/15/you-do-not-need-a-database-for-your-contact-form.html) and thought I'd give it a try, but for reasons I don't understand, it is not working. When I click the submit button, nothing happens. Any idea how to get this working?

**Comment by mmistakes** [comment]
Not sure. I've never used Formspree.

**Comment by mmistakes** [comment]
Have you asked for help here? https://talk.jekyllrb.com/t/formspree-functional-html-forms/263

**Comment by misterpark** [comment]
No, I emailed Formspree support, but the response was not overly helpful. I shall try the Jekyll forum. Thanks for the heads up.

**Comment by misterpark** [comment]
I've opened a thread on the Jekyll to explore this. I will update here if I find a solution: https://talk.jekyllrb.com/t/formspree-contact-form-not-working/295
