### ISSUE TITLE
Search Tags

### ISSUE THREAD

**Issue by ahmadgit** [mmistakes/so-simple-theme#142]
Hi:

How should search.json be modified to search into post tags as well? I tried the following but it does not work:

[
{% for post in site.posts %}
  {% if post.title != null and post.title != empty and post.search_omit != true %}
    {% if forloop.index > 1 %},{% endif %}{
      "title"			: {{ post.title | jsonify }},
      "link"			: "{{ site.url }}{{ post.url }}",
      "excerpt"		: "{{ post.excerpt }}",
      "tags"		: "{{ post.tags }}"
    }
  {% endif %}
{% endfor %}

{% for page in site.pages %}
  {% if page.layout != 'none' and page.layout != 'none' and page.title != null and page.title != empty and page.search_omit != true %}
    {% if forloop.index > 1 %},{% endif %}{
      "title"			: {{ page.title | jsonify }},
      "link"			: "{{ site.url }}{{ page.url | replace: 'index.html', '' }}",
      "excerpt"		: "{{ page.excerpt }}",
      "tags"		: "{{ post.tags }}"
    }
  {%endif%}
{% endfor %}
]

is it because tags is an array?

**Comment by mmistakes** [comment]
Since you added tags to the `search.json` file the Javascript that does the heavy lifting doesn't know anything about post tags. You'll need to modify [`search.js`](https://github.com/mmistakes/so-simple-theme/blob/master/assets/js/plugins/search.js) to also search tags and then rebuild `scripts.min.js` using the included Grunt task.

**Comment by ahmadgit** [comment]
thanks for your reply. So I have added the following to search.js:

function populateResultContent(html, item) {
    html = injectContent(html, item.title, '##Title##');
    html = injectContent(html, item.link, '##Url##');
    html = injectContent(html, item.excerpt, '##Excerpt##');
    html = injectContent(html, item.date, '##Date##');
    html = injectContent(html, item.tags, '##Tags##');
    return html;
}

and I also rerun grunt, but still the search does not include tags. Do I need to change anything else?

**Comment by mmistakes** [comment]
Not sure. I didn't write the script. I'd file an issue or reach out the author of the [Jekyll Search setup](https://github.com/mathaywarduk/jekyll-search) I included with So Simple since they'd have a better idea of what's going wrong.
