### ISSUE TITLE
Social buttons not showing up

### ISSUE THREAD

**Issue by handoftheking** [mmistakes/so-simple-theme#150]
I can see the related code added to the html but no image or text appear 
Anything special to do besides putting ``share: true`` in the post .md meta-data ?

**Comment by mmistakes** [comment]
If you see the code in the HTML the chances are you're running an Adblock extension in your browser. If that's the case depending on which one you have installed there are settings to tweak disabling social sharing widgets.

**Comment by handoftheking** [comment]
Duh. Make sense. Thanks.
