### ISSUE TITLE
Any best practices regarding multi languages blog?

### ISSUE THREAD

**Issue by Kraymer** [mmistakes/so-simple-theme#153]
I'd like to have 2 versions of my website *en* and *fr*.
Creating a ``fr`` directory in ``_posts`` will work but how about the search functionality? is there a way to restrict it to a subset of the site (search restricted to all pages in a given langage).

**Comment by mmistakes** [comment]
Probably but you'll have to build that logic into the search. The way it's working now is [a JSON file](https://github.com/mmistakes/so-simple-theme/blob/master/search.json) is created by looping over every post and then some Javascript reads that to build the results.

Maybe look into some of the other Jekyll search options (just Google around) and they might offer more ways to filter.

Another option would be to create two search pages (English & Francais) and two JSON files (en and fr). In the JSON files you'd simply modify the Liquid for loop to include only the appropriate posts. Not sure how you're flagging *en* and *fr* posts but if you did it in their YAML you could use something like:

```
{% assign english_posts = (site.posts | where: "language" , "en") %}
{% for post in english_posts %}
  {% if post.title != null and post.title != empty and post.search_omit != true %}
    {% if forloop.index > 1 %},{% endif %}{
      "title"			: {{ post.title | jsonify }},
      "link"			: "{{ site.url }}{{ post.url }}",
      "excerpt"		: "{{ post.excerpt }}"
    }
  {% endif %}
{% endfor %}
```

**Comment by mmistakes** [comment]
Also this is a very good blog post by Development Seed about [how they handle multilingual sites in Jekyll](https://developmentseed.org/blog/multilingual-jekyll-sites/). I personally haven't done this type of site with Jekyll yet so can't offer much assistance, but hopefully the post will lead you in the right direction.

**Comment by Kraymer** [comment]
thks the blog post is gold
