### ISSUE TITLE
Search form event handler causes TypeError

### ISSUE THREAD

**Issue by edgenard** [mmistakes/so-simple-theme#155]
Hi, I am trying to use this theme to style my site and it looks great. I have form though that when submit gets pressed I get `Uncaught TypeError: Cannot read property 'toLowerCase' of undefined` at `scripts.min.js:1`. I would like to try to debug this but I cannot read the minified JS. Is there a way to get the unminified versions? I thought it has something to do with the `Grunt` file but I don't have much experience using it and I don't want to break anything.

Thanks

**Comment by edgenard** [comment]
I think I found out why

```javascript
 $(document).on("submit", $searchForm, function(a) {
    a.preventDefault(), q = $searchInput.val(), execSearch(q)
  })
}
```
This is triggering the event listener that should only be for the search form on any submit, it seems that any form triggers this and not just forms

I change `$searchForm` to `.simple-search` and everything looks like it still works, without affecting other forms on the site.

**Comment by mmistakes** [comment]
All of the unminified scripts are in the [`js` folder](https://github.com/mmistakes/so-simple-theme/tree/master/assets/js). Grunt is used to take all of them, combine them, and then minify into `scripts.min.js`.

**Comment by suchja** [comment]
Maybe I do have a similar problem. I'm trying to run a simple form action. However, when I click on the button nothing happens. I tried my form action without jekyll & theme in a plain html page and it works smoothly.

Once I remove `search.js` and minify everything again with grunt, `submit` works as expected. Actually it is not enough to simply set `search: false` in `_config.yml`.

@edgenard  I do not understand what you did with `$searchForm`. Could you explain how exactly you changed the javascript so `submit` does not work only for the search? I do have no experience with js, so thanks for your input.

**Comment by edgenard** [comment]
The way search.js is written it listens for submit event on any form on the whole site. So it triggers the `function(a)`:

```javascript
 $(document).on("submit", $searchForm, function(a) {
    a.preventDefault(), q = $searchInput.val(), execSearch(q)
  })
}
```
So what I did is I changed what `$searchForm`  refers to. It used to refer to in `search.js` You'll find
 `$searchForm = $("[data-search-form]")` I changed it to ` $searchForm = $(".simple-search")`. This narrows it down to just the search form, not every form on the site.

**Comment by suchja** [comment]
Now got it working as @edgenard suggested. I changed the registration of the event handler for `submit` from `$searchForm` to `".simple-search"`. Not sure whether search still works, but finally at least my form is working.

@mmistakes  Would it be possible to get this fixed in the theme? It took me quite some time to figure out. Unfortunately I'm not experienced in javascript, so I do not have any idea about the impact of the change. Otherwise I could make a pull request. Any input?

@edgenard Thanks! and sorry, I should improve my javascript knowledge! Additionally some thinking before posting would be good as well.

**Comment by mmistakes** [comment]
@suchja I'm far from a Javascript expert myself. If you want to submit a pull request with the fix I'd be happy to look at it and merge.

**Comment by jabhishek** [comment]
I have submitted a PR to fix this.
