### ISSUE TITLE
Add cookie consent module

### ISSUE THREAD

**Issue by fabriziofortino** [mmistakes/so-simple-theme#156]
https://www.cookiechoices.org/

**Comment by pstavirs** [comment]
Any update or plan on this? I see Pull Request #163 open for this feature.

**Comment by mmistakes** [comment]
Probably not. I'm only interested in adding features or enhancements that most people will want. This falls in the category of something you can add yourself and customize it if you need it.

**Comment by pstavirs** [comment]
Since cookie consent is now required as per AdSense TOS, the existing AdSense support feels incomplete :-)

If its something you don't wish to do, that's fair enough! Thank you for your work!

**Comment by mmistakes** [comment]
It's not something I feel belongs in the theme and rather should be something you customize and add yourself. I'm trying to balance these sorts of requests out. I merge it in and I likely get requests to make it toggle-able or customize it further (style, color, behavior, etc).

I'd rather leave it to those forking and cloning the theme to determine if it's important to them and take it from there. Can't possibly please everyone :stuck_out_tongue:
