### ISSUE TITLE
Rakefile

### ISSUE THREAD

**Issue by justinmoh** [mmistakes/so-simple-theme#158]
Is there suppose to be a rakefile included?

**Comment by justinmoh** [comment]
I guess I got it. A rakefile is not necessary.

Octopress can generate post by reading its configuration from _config.yml, so just copy the content of _octopress.yml into _config.yml then octopress can produce expected result.

**Comment by mmistakes** [comment]
that sounds about right. I haven't looked at Octopress in awhile so check its docs. Back when I added the gem to the theme it was in beta and it had its own config file.
