### ISSUE TITLE
LateX/ MathJaX support with so-simple

### ISSUE THREAD

**Issue by sachinruk** [mmistakes/so-simple-theme#159]
Hi,

I tried to get mathsymbols to work as suggested in: http://christopherpoole.github.io/using-mathjax-on-github-pages/ but with no-luck. I added the mathjax script in "head.html" and tried this with no luck. Any chance we could get a minimal example? eg. $x^2$ ought to show x squared.

Cheers

**Comment by mmistakes** [comment]
I followed the instructions provided by your link and it worked perfectly fine for me. Perhaps you didn't properly escape the maths as the blog post suggested?

Here's a working [MathJax example with So Simple](https://mmistakes.github.io/so-simple-theme/blog/mathjax-example/).

![mathjax](https://cloud.githubusercontent.com/assets/1376749/9171574/c6b290e0-3f3a-11e5-9462-4f16891c826a.jpg)

**Comment by sachinruk** [comment]
Hi,

Sorry to bother you one last time but I was actually having trouble having multi-line equations with this update. For example, as per latex I really wanted to use:
$$
\begin{align}
y=x+1\\
z=y+2
\end{align}
$$
but this wouldn't render. The dollar sign AND the multiline wasn't well recieved. 

I finally found the solution in: http://stackoverflow.com/questions/11228558/let-pagedown-and-mathjax-work-together/11231030#11231030. Basically I added the js file http://cdn.sstatic.net/js/mathjax-editing.js in assets/js/plugins and this fixed the issue. Now inline maths can use $$x^2$$ and multiline with wth the code above.

Cheers

**Comment by a2nr** [comment]
Hi, 

firstly, i like to use the theme as my personal blog. I am currently write using latex and thanks the basic is working and '\begin{equation}' is working too, but i cant using `\eqref{}` even '\label{}' was created under '\begin{equation}'. i was searching of solution but i don't know how to add the script by default.
[Here](http://flennerhag.com/2017-01-14-latex/) is the solution. 

Regards,
