### ISSUE TITLE
Removing the favicon

### ISSUE THREAD

**Issue by callmeskywalker** [mmistakes/so-simple-theme#165]
I have deleted all the favicon images.
I tried adding my own favicon (16px x 16px) 
The original favicon still appears. 

I removed my favicons. 
Somehow when I delete the originals, they are still appearing as the favicon.

Deleted these:
https://github.com/mmistakes/so-simple-theme/blob/master/favicon.ico 
https://github.com/mmistakes/so-simple-theme/blob/master/favicon.png

As well as the apple touch icons from here:
https://github.com/mmistakes/so-simple-theme/tree/master/images

It seems that the favicon calls are happening here (lines 47-57):
https://github.com/mmistakes/so-simple-theme/blob/master/_includes/head.html#L47-L49

It's perplexing to me that with all of those things deleted I am still getting the original favicon. 
How can I fix this? 

It's not as simple as restarting the server, I tried that a few times.

**Comment by mmistakes** [comment]
Your browser probably has the old ones cached. Try flushing it.

**Comment by callmeskywalker** [comment]
Trick of the trade. Thanks
