### ISSUE TITLE
trouble getting website running via github server

### ISSUE THREAD

**Issue by callmeskywalker** [mmistakes/so-simple-theme#166]
Running `bundle exec jekyll build` and `bundle exec jekyll serve`, my website works perfectly fine on my local machine. 

It is not working on the github server.
Here is [the link to my website's repository](https://github.com/callmeskywalker/callmeskywalker.github.io).
When I visit [my website](http://callmeskywalker.github.io/), a basic view loads and all the links give errors. 
 
This is my first time setting up a website on github and with Jekyll, so I am sure it is something stupid with config settings, probably in *_config.yml*.

Can someone help me identify the problem?  

Here is some of the troubleshooting I have found and tried:
----

I checked out [trouble shooting github pages](https://help.github.com/articles/troubleshooting-github-pages-build-failures/).
I have definitely verified my email. 
None of the other generic failures seem relevant.

Perhaps, this could be the issue, [adding the Jekyll plugins that are being used to _config.yml](https://help.github.com/articles/using-jekyll-plugins-with-github-pages/). 

I also checked out the [basic reference for using Jekyll with github](https://help.github.com/articles/using-jekyll-with-pages/#using-jekyll). 
I am already working via the `bundle exec` commands. 
I installed the `github-pages` gem, and ran `bundle install`. 
It installed quite a few packages.

I tested with `github-pages` installed on my local machine, the website still worked fine. I tested with it on the github server but it was still not working. Again, as I am a complete noob, I am sure it is something stupid.

**Comment by mmistakes** [comment]
What exactly are the errors you're seeing? I just went to your site and it appears to load just fine for me.

**Comment by callmeskywalker** [comment]
It is working now.
