### ISSUE TITLE
markdown display issue when add code block to list

### ISSUE THREAD

**Issue by liuzxc** [mmistakes/so-simple-theme#174]
I am try to add code block to markdown list, but display incorrect.

```markdown
1. first

2. second

    {% highlight ruby %}
    def foo
      puts 'foo'
    end
    {% endhighlight %}

3. third
```

![2015-10-29 6 39 28](https://cloud.githubusercontent.com/assets/1954295/10816264/700b76fa-7e6c-11e5-9899-0d3cf1ee712e.png)

but if I write like this, it is no problem.

```markdown
1. first

2. second

    ```
    def foo
      puts 'foo'
    end
    ```

3. third
```

![2015-10-29 6 41 37](https://cloud.githubusercontent.com/assets/1954295/10816311/e1da015c-7e6c-11e5-8544-f59fd41742a7.png)

Is this pygments problem?

**Comment by mmistakes** [comment]
Yeah I think it's either related to Kramdown or Pygments. I couldn't get it to work either. Using fenced blocks like you have in the second example sort of works, but you don't get the syntax highlighting and it's not outputting `<pre></pre>` around the `<code>` elements.

Not really sure if I have a solution. Sorry.
