### ISSUE TITLE
page.path is retrieving post.path + page.path

### ISSUE THREAD

**Issue by geyslan** [mmistakes/so-simple-theme#175]
I'm trying to include a link to my github .md in every post, so in post.html I coded:
```
This post was created in markup language. You can find it <a href="{{ page.path }}" target="_blank"><b>here</b></a>.
```
The link is being created with post.path + page.path : `http://127.0.0.1:4000/blog/un-building-software-part-2/_posts/blog/2015-10-27-un-building-software-part-2.md`

I expected only `_posts/blog/2015-10-27-un-building-software-part-2.md`, thus I could concatenate the github url.

Am I doing something wrong?

**Comment by mmistakes** [comment]
Not sure, I've never used `{{ page.path }}`. I'd try asking on [Jekyll Talk](https://talk.jekyllrb.com/). This is more of a Jekyll core question than anything related to the theme. Closing issue for this reason.
