### ISSUE TITLE
text language

### ISSUE THREAD

**Issue by GeekinaCave** [mmistakes/so-simple-theme#181]
hi, i wish to know if the internal text like this:

![captura](https://cloud.githubusercontent.com/assets/8534866/11733843/d193dc4e-9f7f-11e5-9b0e-0a9d8ff7f878.PNG)

and similar are inside a config file witch can be mod or is "hardwire" into the theme.
The reason is because since I´m using tis theme for a blog in spanish i wanted to look more fluid with the main language.

Thanks.

**Comment by mmistakes** [comment]
Parts of it come from variables you set in your `_config.yml`. You can customize it to be whatever you want by editing this line in [`/_includes/footer.html`](https://github.com/mmistakes/so-simple-theme/blob/master/_includes/footer.html#L3)

``` html
<span>&copy; {{ site.time | date: '%Y' }} {{ site.owner.name }}. Powered by <a href="http://jekyllrb.com" rel="nofollow">Jekyll</a> using the <a href="http://mademistakes.com/so-simple/" rel="nofollow">So Simple Theme</a>.</span>
```
