### ISSUE TITLE
Move tags to the bottom of a post

### ISSUE THREAD

**Issue by vicrucann** [mmistakes/so-simple-theme#183]
Dear Michael, thank you for the great jekyll theme. I was wondering if you could provide an example of how to move the tags to the bottom of the page?

**Comment by mmistakes** [comment]
That's pretty easy to do. If you look at `_layouts/post.html` on [line 19](https://github.com/mmistakes/so-simple-theme/blob/master/_layouts/post.html#L19) you'll see the code for the post tags. What you can do is grab the following and move it wherever you want in the layout.

``` html
<ul class="entry-tags">
    {% for tag in page.tags %}<li><a href="{{ site.url }}/tags/#{{ tag }}" title="Pages tagged {{ tag }}">{{ tag }}</a></li>{% endfor %}
</ul>
```
 
I'd suggest placing it right after the `{{ content }}` tag on line 45. Moving it here will give you something like this:

![tags](https://cloud.githubusercontent.com/assets/1376749/11787046/d1555f0c-a257-11e5-989e-9e628a131917.png)

**Comment by vicrucann** [comment]
Thank you!
