### ISSUE TITLE
Is there an easy way to remove a site's title and subtitle from a blog/article page?

### ISSUE THREAD

**Issue by vicrucann** [mmistakes/so-simple-theme#184]
And leave the site's title and subtitle on non-blog pages only.

**Comment by mmistakes** [comment]
There's a bunch of ways you could approach it. Off the top of my head.

1. Add some sort of YAML Front Matter variable to the post/pages you don't want the site title/subtitles to appear on. For example `site-titles: false`
2. Then in [`/_includes/navigation.html`](https://github.com/mmistakes/so-simple-theme/blob/master/_includes/navigation.html#L30) wrap the title lines in a conditional that references the variable from step 1. Perhaps something like this:

``` html
{% if page.site-titles != false %}
  <h1 class="site-title animated fadeIn"><a href="{{ site.url }}/">{{ site.title }}</a></h1>
  <h2 class="site-description animated fadeIn" itemprop="description">{{ site.description }}</h2>
{% endif %}
```

What this is basically saying is when a post/page doesn't have a variable `site-titles` equal to `false` then show the titles.

This approach works well if you want to exclude a handful of pages. You could also do the reverse and opt-in pages with titles and go with `site-titles: true` and `{% if page.site-titles == true %}`.

**Comment by vicrucann** [comment]
Thank you! 
I will try one of the approaches.
