### ISSUE TITLE
Is it possible to assign an automatic reference number to formulas ?

### ISSUE THREAD

**Issue by vicrucann** [mmistakes/so-simple-theme#189]
For example:
[formula reference example](https://en.wikibooks.org/wiki/File:Latex_example_math_referencing.png).

So that it would be possible to refer to a certain formula later in the text like so: "From eq.(1)" and it would make a link to that equation?

**Comment by mmistakes** [comment]
Not sure. I don't have much experience using Latex or formulas with Jekyll. I'd suggest asking on th [Jekyll Talk](https://talk.jekyllrb.com/) forums. Maybe someone there has more experience with them and could help out.

**Comment by vicrucann** [comment]
Got it. I will see what I can find. Thanks.
