### ISSUE TITLE
How to include pagination feature?

### ISSUE THREAD

**Issue by vicrucann** [mmistakes/so-simple-theme#192]
I was trying to figure it out on myself based on [jekyll's doc](http://jekyllrb.com/docs/pagination/), but could not make it work. Would be nice to have the pagination on index page. How difficult is it to incorporate?

**Comment by mmistakes** [comment]
It's not too hard. If you look at my other theme [HPSTR](https://github.com/mmistakes/hpstr-jekyll-theme) for inspiration, I use pagination there. Basically you swap `{% for post in site.posts %}` with `{% for post in paginator.posts %}` and include some pagination links for showing next/previous and you're done.

**Comment by vicrucann** [comment]
I looked at the example, and after a while of tweaking, finally made it work. Thank you!

**Comment by mmistakes** [comment]
Good. Glad you figured it out. :smile:

**Comment by ketingli1** [comment]
i was in trouble for error info:
Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.

but i do as the document tutor, would you help me
