### ISSUE TITLE
search.js interferes with form validation

### ISSUE THREAD

**Issue by espresso-math** [mmistakes/so-simple-theme#194]
Including search.js in every page by compressing it with other js files in the scripts.min.js file leads to this problem.

```
    $(document).on("submit", $searchForm, function(e) {
        e.preventDefault();
        q = $searchInput.val();
        execSearch(q);
    });
```

somehow every time any other form gets submitted this script fires and the form refuses to post although the validation take place just fine. Consider removing this file from script.min.js and placing it only in the search page.

**Comment by pstavirs** [comment]
I also have the same problem.

Any plans for a fix?

**Comment by annegentle** [comment]
I have this problem as well.

**Comment by annegentle** [comment]
I found the fix in this PR on the original jekyll-search repository:

```
$searchForm = "[data-search-form]",
```
See https://github.com/mathaywarduk/jekyll-search/pull/13/files for more details.

**Comment by mmistakes** [comment]
Thanks for the detective work @annegentle.

I've pushed this fix if someone wants to verify that it clears up the problem before I merge it into `master`. Should just have to overwrite your copy of `scripts.min.js` with [this one](https://github.com/mmistakes/so-simple-theme/blob/feature/search-fix/assets/js/scripts.min.js).
