### ISSUE TITLE
Fix SCSS variables

### ISSUE THREAD

**Issue by pstavirs** [mmistakes/so-simple-theme#201]
I'm not a web developer, so I may be mistaken, but I think `spin` is a LESS construct not SASS. The corresponding SASS function is `adjust-hue`

```diff
diff --git a/_sass/_variables.scss b/_sass/_variables.scss
index a63f9da..b587d9d 100644
--- a/_sass/_variables.scss
+++ b/_sass/_variables.scss
@@ -22,7 +22,7 @@ body {
 $body-color         : #fff;
 $text-color         : #222;
 $base-color         : #343434;    
-$comp-color         : spin($base-color, 180); 
+$comp-color         : adjust-hue($base-color, 180);
 $border-color       : #ddd;
 $white              : #fff;
 $black              : #000;
```

**Comment by mmistakes** [comment]
Originally the stylesheets were built with Less and then I converted them to SCSS. I probably just missed this.

**Comment by mmistakes** [comment]
Fixed as of commit https://github.com/mmistakes/so-simple-theme/commit/aadb22ffcfe8aeb0664600c8bf946178fb4cae52
