### ISSUE TITLE
Add an example of table ?

### ISSUE THREAD

**Issue by blunderboy** [mmistakes/so-simple-theme#203]
Can you please add an example of Table in an article ?

For example, I can create a table in markdown like this:

| S.No | Student | Marks |
|-------|--------|--------------|
| 1 | Sachin | 100 |
| 2 | Rahul | 200 |

I want to create a similar table on my site available here: http://requestly.in using So Simple Theme.

**Comment by mmistakes** [comment]
There is a table example. Standard Markdown tables should work just fine. 

https://mmistakes.github.io/so-simple-theme/articles/sample-post/

https://github.com/mmistakes/so-simple-theme/blob/master/_posts/articles/2011-03-10-sample-post.md

**Comment by blunderboy** [comment]
@mmistakes Thanks man!! I see it now.

What is the meaning of this line `{: .table}` ?

**Comment by mmistakes** [comment]
It applies a `.table` class to the `<table>` element for some additional styling. It's a [Kramdown feature](http://kramdown.gettalong.org/quickref.html#block-attributes).

**Comment by blunderboy** [comment]
Thanks @mmistakes. Query is resolved. Closing this issue.
