### ISSUE TITLE
Syntax Highlighting for Python and R 

### ISSUE THREAD

**Issue by eneskemalergin** [mmistakes/so-simple-theme#207]
Hello, 
Thanks for the amazing template, everything works like charm except the syntax highlighting for Python and R

I have tried this:
```
```Python
# Calling numpy as np
import numpy as np
# Creating a point data X, Y
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])```
```

```
~~~Python
# Calling numpy as np
import numpy as np
# Creating a point data X, Y
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])~~~
```

Thanks for the help....

**Comment by mmistakes** [comment]
The problem you're having isn't theme related. Change `Python` to `python` and it will work. My guess Rouge doesn't know what to do with the capitalized `Python`. For a full list of the supported languages and lexers [check here](https://github.com/jneen/rouge/wiki/list-of-supported-languages-and-lexers).

```
    ``` python
    # Calling numpy as np
    import numpy as np
    # Creating a point data X, Y
    X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
    Y = np.array([1, 1, 1, 2, 2, 2])
    ```
```

![python](https://cloud.githubusercontent.com/assets/1376749/15719788/90fda1fc-27ff-11e6-8d94-029c6282b6ef.jpg)

You can also use Jekyll's syntax highlighting with:

```
{% highlight python %}
# Calling numpy as np
import numpy as np
# Creating a point data X, Y
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])
{% endhighlight %}
```

**Comment by eneskemalergin** [comment]
@mmistakes Thanks, I should have tried those before opening this issue, sorry!

**Comment by mmistakes** [comment]
No worries.
