### ISSUE TITLE
Cannot get my site to show properly on github-pages

### ISSUE THREAD

**Issue by EdwinTh** [mmistakes/so-simple-theme#211]
I've built a website for blogging using your wonderful theme, which I want to host on github-pages. All works great locally, however when I run it on github I lose the entire style (I don't know much about front ends, but I guess it only shows the plain html). I am obviously missing something that needs to be done before publishing but I can't figure out what. I hoped you tell me show me.

 [This](https://github.com/EdwinTh/EdwinTh.github.io)  is the link to my repo. Thanks in advance!

**Comment by mmistakes** [comment]
Try setting `url` in your `_config.yml` with https instead.

```
url: https://EdwinTh.github.io
```

Your site has is being redirected to the https secured version but your assets (CSS and JS) are being served insecurely. Which the browser blocks and doesn't load.

![screen shot 2016-08-06 at 11 04 00 pm](https://cloud.githubusercontent.com/assets/1376749/17460208/1a55dc5e-5c2a-11e6-9caf-a01420ff800a.png)
