### ISSUE TITLE
Change featured image position 

### ISSUE THREAD

**Issue by danielmarcelino** [mmistakes/so-simple-theme#212]
Hi, this is more a curiosity than an issue question. Is it possible to make featured images to appear in front of the menu without any logo image? Can you pinpoint the right part I could change to achieve this, please? 
Here is my blog: http://danielmarcelino.github.io

**Comment by mmistakes** [comment]
To change the order of appearance edit the `post.html` and `page.html` `_layouts`. They're very similar.

The navigation menu pulls in with `{% include navigation.html %}` and the feature images come in a few lines below it with:

```liquid
{% if page.image.feature %}<img src="{{ site.url }}/images/{{ page.image.feature }}" class="entry-feature-image" alt="{{ page.title }}" {% if site.logo == null %}style="margin-top:0;"{% endif %}
```

You can try shuffling those lines around and see if things display how you want. You'll likely need to finesse the CSS some too on those elements as the spacing and alignment might get screwy.
