### ISSUE TITLE
Adding captions to images

### ISSUE THREAD

**Issue by PerrinWaldock** [mmistakes/so-simple-theme#214]
Hi,

Template looks beautiful, but I've been having some issue with captions.

I'm a beginner with CSS and HTML, but have some coding experience with unrelated languages like Java, C++, and Python. I'm trying to add captions to images displayed in a row using the "third" format, but haven't found a good way to do it. Using figcaption just results in issues with how the images are floating; they end up aligning themselves diagonally.

I'd be happy with either superimposing text onto the images or having a caption above or below, but haven't figured out how to do that with "third".

Thanks!

**Comment by mmistakes** [comment]
Have you looked at the sample post? It has examples for `half` and `third`, both with captions. 

https://mmistakes.github.io/so-simple-theme/articles/sample-post-images/

**Comment by PerrinWaldock** [comment]
Thanks, but I'm actually hoping for individual captions for each image rather than one encompassing all of them.

**Comment by mmistakes** [comment]
The theme doesn't currently support that. According to the HTML spec for `figcaption` it appears

> As the first or last child of a figure element.

If you want to caption every image you'll need to find another solution.

The theme does include the [MagnificPopup](http://dimsemenov.com/plugins/magnific-popup/) lightbox script, that supports captions. I believe you have to markup image links with the `title` attribute and then it'll automatically include them below each image.

![screen shot 2016-09-02 at 6 57 53 am](https://cloud.githubusercontent.com/assets/1376749/18201866/a51bd27a-70da-11e6-9a16-a1432c79058d.png)
