### ISSUE TITLE
Header pops into place

### ISSUE THREAD

**Issue by JarrydHuntley** [mmistakes/so-simple-theme#223]
On IE, Edge, Chrome, and Safari there is a weird header weird "pop-in(?)" upon page load. All elements are shifted down immediately.

It's most evident on this page https://mmistakes.github.io/so-simple-theme/theme-setup/, but effects all pages in the theme. 

It may be related to the following CSS selector
```
#site-nav {
    display: none;
    z-index: 5
}
```

Firefox seems to be unaffected.

Please let me know if you need any more info.

Thanks much!

**Comment by rafaelbiriba** [comment]
following!

**Comment by mmistakes** [comment]
I am unable to reproduce this behavior. If I had to guess it's due to the large hero images reflowing the page as they load.

The theme has been completely rebuilt, if you're still noticing the issue in v3.0 and can provide more details on how to reproduce feel free to reopen.
