### ISSUE TITLE
Increase the width of the articles

### ISSUE THREAD

**Issue by sainathadapa** [mmistakes/so-simple-theme#226]
What do I need to change to increase the width of the blog/posts? I feel the default width is too small, for laptop/pc screens.

**Comment by mmistakes** [comment]
The CSS. I'd suggest firing up your browsers web developer tools to inspect the various elements. It will show you what CSS has been applied and then you can do a search in the sourcecode for that element or class to modify.

You'll likely want to [look at this line](https://github.com/mmistakes/so-simple-theme/blob/master/_sass/_page.scss#L107) on `.entry-wrapper` which uses a [mixin from Bourbon Neat](http://thoughtbot.github.io/neat-docs/latest/#outer-container) to set a `max-width` of `60em`. Bumping that up should made it wider.

**Comment by sainathadapa** [comment]
Thanks! I was able to change the width using css.
