### ISSUE TITLE
[Solved]Display Mismatch

### ISSUE THREAD

**Issue by aaronxu17** [mmistakes/so-simple-theme#233]
Hi, Michael!

Sorry to bother you! I found I can use your theme very well when I test it locally (http://localhost:4000). But when I push it to my repo. The display is very weird when I access via (url: https://aaronxu17.github.io). Can you take a look and analyze what happened? Thanks!

<img width="1029" alt="display_error" src="https://cloud.githubusercontent.com/assets/11140417/24488224/6db0f8d0-14e3-11e7-93b8-788539d18d38.png">

**Comment by shanmdphd** [comment]
Please change your `url: http://aaronxu17.github.io` in the `_config.yml` file to `url: https://aaronxu17.github.io` then you can probably solve the problem.

**Comment by aaronxu17** [comment]
Works! thanks!
