### ISSUE TITLE
URLs generated from _posts

### ISSUE THREAD

**Issue by jjvenky** [mmistakes/so-simple-theme#242]
First, thanks for the theme. It looks great and is easy to use.

I have a scenario where I might use the same categories for multiple files in  _posts/ that end up being served via mysite/articles/. In this case I have two files, 2017-06-01-post-1.md and 2017-06-15-post-2.md. Both have two categories at the top of each file like ```categories: research myproject```. But both end up being served as mysite/research/myproject. So I'm looking for a fix/workaround to have unique URLs generated in this scenario. Perhaps with the date or title baked into the URL.

Thanks.

**Comment by mmistakes** [comment]
Take a look at the [Jekyll docs](http://jekyllrb.com/docs/permalinks/). You can override the permalinks if you want by adding something like this to the post's YAML Front Matter.

```
permalink: /custom-url/
```

**Comment by jjvenky** [comment]
Perfect. Thank you!
