### ISSUE TITLE
Unexpected end tag

### ISSUE THREAD

**Issue by KirstieJane** [mmistakes/so-simple-theme#245]
Hi @mmistakes. In the [travis log](https://travis-ci.org/WhitakerLab/whitakerlab.github.io/jobs/243670045) of [my fork](https://github.com/WhitakerLab/whitakerlab.github.io) of your **beautiful** theme there is an `Unexpected end tag : a (line 137)`.

I think this is to do with [this section (lines 33 & 35)](https://github.com/mmistakes/so-simple-theme/blob/master/_layouts/post.html#L32) in the [_layouts/post.html](https://github.com/mmistakes/so-simple-theme/blob/master/_layouts/post.html) file.

From what I can see the error would be fixed by either removing the `</a>` tag at the end of lines 33 & 35, or by adding in the `<a hef=...>` that's missing.

Do you have any thoughts? I'm happy to submit a pull request if you can let me know which option is cleanest 😀 . Thank you again for the wonderful theme!

**Comment by mmistakes** [comment]
Looks like a bug to me. There were originally opening `<a>` elements on lines 33 and 35 that I removed at some point, and must have forgotten the closing tags.

Feel free to support a PR that takes `</a>` out on both of those lines and I'll merge it in :smile:

**Comment by georgeluong** [comment]
I ran into bug, and came across this bug. Sorry if I'm stepping on anyone's toes, but I created a PR for this! https://github.com/mmistakes/so-simple-theme/pull/246.

**Comment by KirstieJane** [comment]
Thank you @georgeluong!! I completely forgot about this bug - I was supposed to do the work and didn't! Thank you for picking up the slack 🎉

**Comment by mmistakes** [comment]
Fixed in #246
