### ISSUE TITLE
Add collection with grid

### ISSUE THREAD

**Issue by raquelredo** [mmistakes/so-simple-theme#249]
Hi!
I tried to add a collection for my projects. So Far, I managed to do that. But how do I change my main page to show as a grid with teaser images? I tried to create a different layout for it, but I did not success (my knowledge of Jekyll is basic). Thanks!

**Comment by mmistakes** [comment]
This feature has been added and will land in #265 once merged.

**Comment by mmistakes** [comment]
See [updated layout documentation](https://github.com/mmistakes/so-simple-theme/tree/3.0.1#layouts) for grid usage.
