### ISSUE TITLE
Serious "Page Build Failure Occur" Recently

### ISSUE THREAD

**Issue by leimao** [mmistakes/so-simple-theme#250]
I have been using this so-simple-theme for more than half-year and it worked very well. I would like to thank you, the author, here. 

However, when I was updating my post today, I found "Page Build Failure" email from Github. I did some troubleshooting then. I deleted the whole site, replaced the site with a empty so-simple-theme, I still got "Page Build Failure" email from Github. However, if I replaced the site with another empty theme. Everything works very well. So I guess there are some updates on Jekyll or Github that makes this theme no longer be supported. Please fix this if you have time. Thank you very much.

**Comment by othreecodes** [comment]
Any luck with this yet @leimao @mmistakes ? I'm having the same issue here

**Comment by othreecodes** [comment]
I got this after updating all gem dependencies
```bash
Configuration file: /root/livewebsites/dod/_config.yml
            Source: /root/livewebsites/dod
       Destination: /root/livewebsites/dod/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Invalid scheme format: {"feature"=>"so-simple-sample-image-7.jpg", "credit"=>"WeGraphics", "creditlink"=>"http in feed.xml
jekyll 3.5.2 | Error:  Invalid scheme format: {"feature"=>"so-simple-sample-image-7.jpg", "credit"=>"WeGraphics", "creditlink"=>"http

```

**Comment by leimao** [comment]
Hi, I won't be having a Linux machine to trouble on Jekyll by September. I am only hoping that someone could fix this.

**Comment by othreecodes** [comment]
```markdown
plugins:
  - jekyll-sitemap
  - jekyll-gist
  # - jekyll-feed
```

I just commented out jekyll-feed...seems like a temporary fix, but it works

**Comment by leimao** [comment]
Sounds great. @othreecodes

**Comment by georgerichardson** [comment]
+1 to thanks for providing this theme!

Also having the same issue. Commenting out `- jekyll-feed` works but probably not a long term solution...

**Comment by mmistakes** [comment]
This doesn't appear to be a theme issue. I'd suggest filing a bug with [jekyll/jekyll-feed](https://github.com/jekyll/jekyll-feed) since it looks like there's an with how it's parsing the `image` front matter.

**Comment by mmistakes** [comment]
If you're still having trouble you'll want to do this:

1. Remove your `Gemfile.lock`... start fresh
2. Make sure you're using the GitHub Pages gem in your `Gemfile` and not Jekyll. Doing so allows you to test locally with the exact same set of dependencies GH uses which will help you trouble shoot. Clean `gem "jekyll"` and any other plugins with just this:
  ```
  gem "github-pages", group: :jekyll_plugins
  ```
3. Run `bundle update`
4. Reenable `jekyll-feed` plugin in your `_config.yml` if you haven't already.
5. Run `bundle exec jekyll build`.

@othreecodes I did exactly this with a clone of your repo and it built fine for me. Site built as expected with no errors, `feed.xml` was produced, as was `sitemap.xml`.

Think there might have been some dependency issues with Jekyll and it's various plugins and including them the way you were in the Gemfile was confusing GH Pages.

**Comment by etheleon** [comment]
hi @mmistakes 

Could you elaborate more on point 2

I'm lookin at my Gemfile 

is this what you mean?

```
source "https://rubygems.org"

#gem "jekyll"                                                                                                                                                                                                                                                                                                                                                               
gem "github-pages", group: :jekyll_plugins
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem 'jekyll-compose', group: [:jekyll_plugins]
```

**Comment by mmistakes** [comment]
@etheleon Yes. You can comment `jekyll-sitemap`, `jekyll-gist`, and `jekyll-feed`, as they're dependencies of `github-pages` already.

That gem will load those plugins so you don't need to include them in your `Gemfile`. If you want a full list of what's included with the `github-pages` gem they have it listed here: https://pages.github.com/versions/

**Comment by othreecodes** [comment]
@mmistakes I used your Fix and everything works fine. feed.xml is also generated

**Comment by devtoolsmith** [comment]
Another solution to mention specific old version in Gemfile
`gem "jekyll-feed", "=0.5.1"`

**Comment by jalexvig** [comment]
I love this theme but am still getting this error. Followed [mmistakes steps](https://github.com/mmistakes/so-simple-theme/issues/250#issuecomment-323451633) and getting the same error locally as well as a failed to build error on GitHub... Anyone find another solution?

**Comment by mmistakes** [comment]
@jalexvig The issue is the Jekyll Feed plugin and how it interprets the `image:` YAML Front Matter in posts.

You have 2 choices until they fix the bug.

Don't use `credit` and `creditlink` on an `image`. There are a few sample posts that do this...example:
```yaml
image:
  feature: so-simple-sample-image-7.jpg
  credit: WeGraphics
  creditlink: http://wegraphics.net/downloads/free-ultimate-blurred-background-pack/
```

Instead comment out `credit` and `creditlink` or just remove them.

```yaml
image:
  feature: so-simple-sample-image-7.jpg
  credit: # WeGraphics
  creditlink: # http://wegraphics.net/downloads/free-ultimate-blurred-background-pack/
```

In your `Gemfile` specify a different version of jekyll-feed that worked before the bug eg `gem "jekyll-feed", "=0.5.1"`. The issue with this method is it won't help you much if you're hosting on GitHub Pages. They autoload a different version and there is no way for you to override that.

**Comment by jalexvig** [comment]
Gotcha - everything before before `jekyll-feed 0.8.0` seems to work but as you mentioned that's not particularly useful info if uploading to GitHub pages.

Thanks for the speedy reply... Will comment those lines out.

**Comment by mmistakes** [comment]
Filed an issue https://github.com/jekyll/jekyll-feed/issues/191

**Comment by woshixiaoou** [comment]
@mmistakes You mentioned:
Don't use credit and creditlink on an image. There are a few sample posts that do this...example:

image:
  feature: so-simple-sample-image-7.jpg
  credit: WeGraphics
  creditlink: http://wegraphics.net/downloads/free-ultimate-blurred-background-pack/

Where can comment out the credit and creditlink for each pages?

**Comment by mmistakes** [comment]
@woshixiaoou In a post's YAML Front Matter. Easiest fix would be to just remove the sample posts from you repo as I'm not sure why you'd keep those.

Or just go through any post's that give the error and remove the `credit` and `creditlink` lines. Or drop a `#` in front of the strings like this:

```yaml
image:
  feature: so-simple-sample-image-7.jpg
  credit: # WeGraphics
  creditlink: # http://wegraphics.net/downloads/free-ultimate-blurred-background-pack/
```

**Comment by mmistakes** [comment]
Or as [per this comment](https://github.com/jekyll/jekyll-feed/issues/191#issuecomment-334827787) on **jekyll/jekyll-feed** add a `path` to the `image` object. For this to work you'll need to add the full path, which means prepending the filename used in `feature` with `/images/`.

Example:

```yaml
image:
  feature: so-simple-sample-image-7.jpg
  path: /images/so-simple-sample-image-7.jpg
  credit: WeGraphics
  creditlink: http://wegraphics.net/downloads/free-ultimate-blurred-background-pack/
```

If you have no need for a credit by line, then omitting those is the best solution. Otherwise you're going to be duplicating some of the variables (`image.feature` and `image.path`).

**Comment by woshixiaoou** [comment]
Hi Michael,

Thank you so much for your reply. Im very new for the jekyll and I love
your so simple site. I fork it to my github and change to gh-pages. The
link is below:
https://woshixiaoou.github.io/blogTutorial/

I try to modify the _config.yml
<https://github.com/woshixiaoou/blogTutorial/blob/gh-pages/_config.yml> file,
but I don't know why nothing change.

But if I download the how package to local and my local host run correctly.
So do you know how to upload my local package to github and use
https://woshixiaoou.github.io/blogTutorial as url address?

**Comment by woshixiaoou** [comment]
Hi Michael,

I got some problems here, could you please take a look of my post page:
https://woshixiaoou.github.io/cloverHabitat/articles/photo-workshop-@Jeffrey-Pedestrian-Bridge,-Irvine/

I'm not sure why, above the menu, there is another title "Clover Habitat"
link to "page not found". This is only happens at each articles and blog
pages.

**Comment by woshixiaoou** [comment]
Hi Michael,

ignore my previous email. fix it. Thank you.

**Comment by woshixiaoou** [comment]
Hi Michael,

I use your so simple for a blog, if you have time, could you please take a
look of following post?
https://woshixiaoou.github.io/cloverHabitat/articles/photo-workshop-@Jeffrey-Pedestrian-Bridge,-Irvine/

How to not use the opacity for the images? I try to remove the opacity from
the following file, but seems nothing change.
https://github.com/woshixiaoou/cloverHabitat/blob/gh-pages/_sass/_elements.
scss
<https://github.com/woshixiaoou/cloverHabitat/blob/gh-pages/_sass/_elements.scss#L27>

**Comment by mmistakes** [comment]
@woshixiaoou Please open a new issue as this has nothing to do with three current one.
