### ISSUE TITLE
Problem with CSS: Please help

### ISSUE THREAD

**Issue by ejaffee01** [mmistakes/so-simple-theme#251]
I am not sure whats wrong with my style.css, I was wondering if someone could help me. There are no errors locally but when I push it to GitHub I get a build error saying this. 

> 
 SCSS file `Desktop/my-blog/css/style.scss` has an error on line 1: File to import not found or unreadable: ../_sass/bootstrap. Load path: /hoosegow/.bundle/ruby/2.4.0/gems/jekyll-theme-primer-0.4.0/_sass.

> 

Please help!!

`---
---
@import '../_sass/bootstrap';
@import '../_sass/syntax-highlighting';

%oswald { font-family: 'Oswald', sans-serif; }
%roboto { font-family: 'Roboto Condensed', sans-serif; }

body {
    @extend %roboto;
    font-size: 18px;
    line-height: 30px;
    padding-top: 51px;
    -webkit-font-smoothing: antialiased;
}
p {
    margin-bottom: 30px;
}
section, header, footer, main, article, nav, aside { position: relative; }
a {
    outline: none !important;
    text-decoration: none !important;
    transition: all 225ms ease;
    color: rgb(19, 100, 214);

    &:hover { color: #6165FF; }
}
.btn {
    text-transform: uppercase;
    font-weight: 400;
    @extend %oswald;
}
h1, h2, h3, h4, h5, h6 { @extend %oswald; }
::selection {
    background: #086AFF;
    color: #fff;
}
nav.navbar {
    margin: 0;

    a {
        text-transform: uppercase;
        font-size: 16px;
    }

    .navbar-brand {
        text-transform: none;

        i {
            transition: inherit;
            color: rgb(19, 100, 214);
            transform: scale(1);
        }

        &:hover i {
            color: rgb(19, 100, 214);
            transform: scale(1.35);
        }
    }
}
.title-group {
    text-align: center;
    padding: 0 15px;
    margin: 50px 0 100px;

    p {
        max-width: 800px;
        margin: 25px auto 0;
    }
}
h1.special {
    position: relative;
    text-align: center;
    overflow: hidden;
    margin: 4;
    text-transform: uppercase;
    @extend %oswald;
    font-size: 69px;
    line-height: 69px;
    font-weight: 700;
    color: rgb(19, 100, 214);

    span {
        display: inline-block;
        position: relative;
        padding: 0 15px;
        max-width: 1000px;

        &:before, &:after {
            content: '';
            position: absolute;
            display: block;
            height: 1px;
            background: #e8e8e8;
            width: 99999999px;
            top: 50%;
            transform: translateY(-50%);
        }

        &:before { left: 100%; }
        &:after { right: 100%; }
    }
}

.tile {
    position: relative;
    box-shadow: 0 0.15em 0.35em 0 rgba(0, 0, 0, 0.135);
    margin-bottom: 125px;

    .inner-guts { padding: 50px; }

    h2 {
        margin: 0;
        font-size: 100px;
        font-weight: 400;
        letter-spacing: -0.05em;
        line-height: 100px;
    }

    .featurette {
        position: relative;
        display: block;
        overflow: hidden;
        margin-bottom: 15px;
        width: 100%;
        height: 550px;
        background-color: #e8e8e8;

        .img {
            background-size: cover;
            background-position: 50% 0;
            background-repeat: no-repeat;
            position: absolute;
            display: block;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            transition: all 225ms ease;
            transform: scale(1);

            &:before {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                display: block;
                content: '';
                background: #000;
                opacity: 0.4;
                transition: all 225ms ease;
            }
        }

        iframe {
            position: absolute;
            display: block;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        &:hover {
            .img {
                transform: scale(1.2);

                &:before {
                    opacity: 0.2;
                }
            }
        }
    }

    .excerpt {
        font-size: 35px;
        font-weight: 300;
        line-height: 49px;
        color: #484848;

        p {
            margin: 0;
        }
    }

    .tags {
        position: absolute;
        left: 0;
        top: 100%;
        margin-top: 15px;

        span {
            padding: 1px 5px;
            font-size: 12px;
            line-height: 1.5;
            text-transform: uppercase;
            @extend %oswald;
        }
    }

    .read-more {
        margin-top: 50px;
        width: 100%;
        max-width: 175px;
        position: relative;
        padding-right: 75px;

        i {
            position: absolute;
            right: 15px;
            top: 50%;
            transform: translateY(-54%);
            font-size: 31px;
            line-height: 100%;
        }
    }
}

aside {
    font-size: 17px;
    color: #525252;
    margin: 16px 0;
    @extend %oswald;

    span {
        text-transform: uppercase;
        margin: 0 5px;
    }
}

.site-footer {
    margin-top: 200px;
}

.pagination-wrap {
    text-align: center;
}

.topper {
    height: 500px;
    position: relative;

    .img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        display: block;
        background-size: cover;
        background-repeat: no-repeat;
        background-position: 50%;
    }

    iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        display: block;
    }
}

pre {
    margin: 75px -100px;
}

@media only screen and (max-width : 991px) {
    pre {
        margin-left: 0;
        margin-right: 0;
    }
}

@media only screen and (max-width : 480px) {
    .tile .featurette, .topper {
        height: 300px;
    }

    h1.special,
    .tile h2 {
        font-size: 40px;
        line-height: 44px;
    }

    .tile .inner-guts {
        padding: 15px 25px;
    }

    .tile .excerpt {
        font-size: 22px;
        line-height: 35px;
    }
}
`

Please help!

**Comment by mmistakes** [comment]
This theme doesn't use Bootstrap... at all. So that looks to be your problem as your Sass is trying to include something that doesn't exist.

Looks to me like you may have files from another theme floating around that need a cleanup.
