### ISSUE TITLE
Compact tag cloud

### ISSUE THREAD

**Issue by kerner1000** [mmistakes/so-simple-theme#252]
I would like to make the 'tag cloud' `tags/index.md` more compact. I. e., to reduce the line spacing between the tags.
I see that the tag list is styled with the "tag-box" class, Which seems to be defined in the '_archives.scss' file. I assume I have to regenerate some css files.  Maybe I can touch the already generated files as well?

**Comment by mmistakes** [comment]
Just edit the `.scss` partials in `_sass`. When Jekyll is run it will generate the CSS, you don't need to do anything special.

**Comment by kerner1000** [comment]
Many thanks for the hint, indeed jekyll regenerates files on the fly. Nevertheless, I fail to manage to reduce the line spacing. Changing e.g. to "line-height: 0.1;" has only a minimal effect on the line spacing. Do I have other options?

**Comment by mmistakes** [comment]
That spacing has nothing to do with `line-height`. Open your browser's web development tools and start inspecting elements.

There's bottom margin on the list elements. Remove or change it to alter the spacing.

![margin](https://user-images.githubusercontent.com/1376749/29519241-9afb56ae-864a-11e7-86b3-f7669ec6eb0c.jpg)

**Comment by kerner1000** [comment]
Perfect, thanks a lot!
