### ISSUE TITLE
Dependency Error when running on netlify

### ISSUE THREAD

**Issue by bigdoods** [mmistakes/so-simple-theme#255]
![screenshot from 2017-09-11 16-09-27](https://user-images.githubusercontent.com/3436953/30281922-a6678d06-970b-11e7-86ed-84d17e2f9827.png)

Full error here: https://pastebin.com/FFW1PGjX

When I try to install blog on netlify, I receive the above error. It looks like a dependency issue in the postinstall script but not sure how to debug.

Any tips to resolve greatly appreciated. Thank you!

**Comment by mmistakes** [comment]
All those errors look like they're related to `npm` and node dependencies.

I haven't used Netlify before, but my guess is you have the theme's development [`package.json`](https://github.com/mmistakes/so-simple-theme/blob/master/package.json) in your repo so it's trying to install all those dependencies... and failing on some image libraries used by `grunt-contrib-imagemin`.

If you're not using any of the [grunt tasks](https://mmistakes.github.io/so-simple-theme/theme-setup/#further-customization) to optimize assets then removing `package.json` will probably solve that. If you are using them then you'll need to investigate further with Netlify to see if they offer a way to  use prebuilt binaries for those image libs `npm` is choking on.

I've done something similar with Travis CI, but not sure how Netlify handles it. Pretty sure the problematic binaries are all part of [Imagemagick](https://www.imagemagick.org/script/index.php) so I'd start your search there.

**Comment by bigdoods** [comment]
Removing package.json worked. Thanks

**Comment by pstavirs** [comment]
Just FYI - I ran into the same problem with Netlify as well as locally. The following patch fixes this -
```diff
diff --git a/package.json b/package.json
index a3b4c53..3322914 100644
--- a/package.json
+++ b/package.json
@@ -18,7 +18,7 @@
     "grunt-contrib-jshint": "~0.6.3",
     "grunt-contrib-uglify": "~0.2.2",
     "grunt-contrib-watch": "~0.5.2",
-    "grunt-contrib-imagemin": "~0.2.0",
+    "grunt-contrib-imagemin": "~2.0.1",
     "grunt-svgmin": "~0.2.0"
   }
 }
```
