### ISSUE TITLE
Persistent SCSS file `assets/css/main.scss` causing build failure

### ISSUE THREAD

**Issue by docalexh** [mmistakes/so-simple-theme#258]
Firstly - thanks for the theme - looks great.

Can anyone help? @mmistakes  

Keep getting the following build error:

The page build failed for the `master` branch with the following error:

Your SCSS file `assets/css/main.scss` has an error on line 10: File to import not found or unreadable: variables. Load path: /hoosegow/.bundle/ruby/2.4.0/gems/jekyll-theme-primer-0.5.2/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/.

*the local build works perfectly...*

any help would be much appreciated. 

site location: 
https://github.com/docalexh/docalexh.github.io

**Comment by mmistakes** [comment]
Your fork is incomplete. You're missing the entire [`_sass` folder](https://github.com/mmistakes/so-simple-theme/tree/master/_sass) in your repo which is why it's giving you that error.

**Comment by docalexh** [comment]
silly me, thanks for the fast response, no longer getting error message- **thank you !**
