### ISSUE TITLE
How to remove the opacity of a image in post

### ISSUE THREAD

**Issue by woshixiaoou** [mmistakes/so-simple-theme#259]
Hi Michael, 

I use your so simple for a blog, if you have time, could you please take a look of following post?
https://woshixiaoou.github.io/cloverHabitat/articles/photo-workshop-@Jeffrey-Pedestrian-Bridge,-Irvine/

How to not use the opacity for the images? I try to remove the opacity from the following file, but seems nothing change. 
https://github.com/woshixiaoou/cloverHabitat/blob/gh-pages/_sass/_elements.scss

**Comment by mmistakes** [comment]
Remove this line https://github.com/woshixiaoou/cloverHabitat/blob/gh-pages/_sass/_base.scss#L154
