### ISSUE TITLE
home page loads, other pages do not

### ISSUE THREAD

**Issue by docalexh** [mmistakes/so-simple-theme#260]
Any advice for a problem: 

my home page looks great, but the theme drops off when I try to open the individual pages. 

Thanks: 
Repo here: 
https://github.com/docalexh/docalexh.github.io

**Comment by chipprogrammers** [comment]
You have to first delete **develop** and **master** branch.  For that first of all make gh-pages branch as default branch. Now you have only **gh-pages** branch and you want to edit files of gh-pages branch. Then create a new **master** branch and make it default branch. I believes it will work for you. Have a nice day. You can see this in this video https://youtu.be/WMpSLPJIkU8

**Comment by docalexh** [comment]
thanks for your help!
