### ISSUE TITLE
Make figures smaller and in line with text

### ISSUE THREAD

**Issue by KirstieJane** [mmistakes/so-simple-theme#261]
Hi and thank you so much for the beautiful layout.

I'd like to add pictures inline with some text - for example the picture on the right and text on the left of the page. Is there an easy way to do this? I'm happy to have a play around, I'm just not sure where to start!

Thank you :)

**Comment by mmistakes** [comment]
Have you looked at the image alignment sample post? There are a few alignment classes the theme ships with that can float an image to the right or left with text wrapping around it.
