### ISSUE TITLE
Logo shape

### ISSUE THREAD

**Issue by adina** [mmistakes/so-simple-theme#275]
- [x ] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment information

- **So Simple version:** 
- **Jekyll version:**
- **GitHub Pages hosted site:** yes/no
- **Operating system(s):** 

---

## Expected behavior

Thank you for your theme.  I was wondering if there is a way to change the shape of the logo so its not rounded.  Thank you much!

**Comment by mmistakes** [comment]
Are you comfortable writing CSS?

The [`.site-logo-img` styles](https://github.com/mmistakes/so-simple-theme/blob/master/_sass/so-simple/_global.scss#L108-L125) can be found here for you to override the `border-radius` properties which round the shape.

`border-radius: 0;` would remove it give you a the default square shape.

**Comment by adina** [comment]
Thank you!
