### ISSUE TITLE
Image gallery?

### ISSUE THREAD

**Issue by adina** [mmistakes/so-simple-theme#276]
- [ ] This is a question about using the theme.
- [x] This is a feature request or enhancement.
- [ ] I believe this to be a bug with the theme.
  - [ ] I am using the latest version of the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment information

- **So Simple version:** 
- **Jekyll version:**
- **GitHub Pages hosted site:** yes/no
- **Operating system(s):** 

---

**Comment by mmistakes** [comment]
Have you looked at Jekyll plugins to do this for you?

- [jekyll-gallery-generator](https://github.com/ggreer/jekyll-gallery-generator)
- [jekyll-art-gallery-plugin](https://github.com/alexivkin/Jekyll-Art-Gallery-Plugin)
- [jekyll-photo-gallery](https://github.com/aerobless/jekyll-photo-gallery)
