### ISSUE TITLE
Font Awesome Icons are not loading in GitHub Pages site

### ISSUE THREAD

**Issue by iamchathu** [mmistakes/so-simple-theme#277]
- [x] This is a question about using the theme.
- [ ] This is a feature request or enhancement.
- [x] I believe this to be a bug with the theme.
  - [x] I am using the latest version of the theme.
  - [x] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment information

- **So Simple version:** latest (using remote theme)
- **Jekyll version:**   github-pages (177) / jekyll (= 3.6.2)
- **GitHub Pages hosted site:** yes
- **Operating system(s):**  MacOS 10.13.3

---

## Expected behavior

Font Awesome Icons are not visible in hosted Github page. But working in local environment.

## Steps to reproduce the behavior

Hosted site URL is is https://unity.chathu.me

**Comment by mmistakes** [comment]
Looks like you're using Cloudflare. Have you tried disabling their [Rocket Loader](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-)? It tries to optimize your JavaScript and I have a feeling it's messing with FontAwesome.

This would explain why it works locally.

Closing as this isn't an issue with the theme.

**Comment by iamchathu** [comment]
Yes, I seems Like Rocket Loader is messing with Font Awesome. When I disabled it using custom rules, Icons are working.

Thanks @mmistakes

**Comment by FlightControl-User** [comment]
How did you disable that, because I am having exactly the same issue!
