### ISSUE TITLE
Search page loads without styling on Firefox

### ISSUE THREAD

**Issue by mjago** [mmistakes/so-simple-theme#291]
Hi
I noticed that on `Firefox 59.0.2` the search page on the demo theme https://mmistakes.github.io/so-simple-theme/search/ loads horribly (without styling) until the page is fully loaded and sorts itself out. This _doesn't_ happen on `Chrome`.
Removing the autofocus and setting focus onload fixes it for me:
```javascript
<script>
window.onload = function() {
  document.getElementById("search").focus();
};
</script>
```

And many thanks for such a great, clean theme :+1:

**Comment by mmistakes** [comment]
I'm not seeing this on Firefox 60. Is the issue still present for you?

**Comment by mjago** [comment]
Nope - issue is not present for me on 60.1 :+1:
