### ISSUE TITLE
Hosting on github not applying the theme

### ISSUE THREAD

**Issue by Better-Boy** [mmistakes/so-simple-theme#297]
I have hosted the site on github, when I don't include the '_include' and '_layouts' not will show up, but when I include those 2 folders , everything appears distorted. Why is this happening?

My Git Repo - https://github.com/Better-Boy/Blog
My Site URL - https://better-boy.github.io/Blog/

Where am I going wrong?

**Comment by mmistakes** [comment]
You're not using the theme correctly. When hosting on GitHub Pages you need to install it as a "[remote theme](https://github.com/mmistakes/so-simple-theme#github-pages-method)".

1. In your `_config.yml` change `theme: jekyll-theme-so-simple` to `remote_theme: "mmistakes/so-simple-theme"`
2. Set `url` and `baseurl` correctly in your `_config.yml` so the paths are configured correctly and assets resolve properly:
    ```yaml
    url: "https://better-boy.github.io"
    baseurl: "/Blog"
    ```
3. Remove the folders and all files in `_layouts` and `_includes`

**Comment by Better-Boy** [comment]
Yes, it worked. Simple mistakes. Thanks for your time and effort.
