### ISSUE TITLE
Incomplete Twitter meta tag for image summary

### ISSUE THREAD

**Issue by theclue** [mmistakes/so-simple-theme#307]
Hi,

I've deployed the theme in my new blog at https://theclue.github.io/bashebiscotti/ and this works like a charm (tnx for this!)

however, I've noticed that the Twitter meta tags are not correctly fed into the page, while OpenGraph actually are. Should this be handled by jekyll-seo-plugin?

example to see a post with hero but without Twitter meta: https://theclue.github.io/bashebiscotti/devops/2018/09/18/rstudio-server-kubernetes.html

tnx allot and have a nice day,
gabriele

**Comment by mmistakes** [comment]
Yes, this all comes from Jekyll's SEO tag plugin, the theme has nothing to do with them.

Looking at your `<head></head>` I see the follow meta tags. Looks complete to me. What exactly is missing?

```
<!-- Begin Jekyll SEO tag v2.5.0 -->
<title>RStudio Server su Google Kubernetes Engine | { Bash e biscotti }</title>
<meta name="generator" content="Jekyll v3.7.4" />
<meta property="og:title" content="RStudio Server su Google Kubernetes Engine" />
<meta name="author" content="Gabriele Baldassarre" />
<meta property="og:locale" content="it" />
<meta name="description" content="RStudio è un popolare ambiente di sviluppo per il linguaggio R. In questo articolo vedremo come utilizzarlo in un cluster Kubernetes." />
<meta property="og:description" content="RStudio è un popolare ambiente di sviluppo per il linguaggio R. In questo articolo vedremo come utilizzarlo in un cluster Kubernetes." />
<link rel="canonical" href="https://theclue.github.io/bashebiscotti/devops/2018/09/18/rstudio-server-kubernetes.html" />
<meta property="og:url" content="https://theclue.github.io/bashebiscotti/devops/2018/09/18/rstudio-server-kubernetes.html" />
<meta property="og:site_name" content="{ Bash e biscotti }" />
<meta property="og:image" content="https://theclue.github.io/bashebiscotti/assets/immagini/rstudio-kubernetes-header.jpg" />
<meta property="og:type" content="article" />
<meta property="article:published_time" content="2018-09-18T00:00:00+00:00" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="@bashebiscotti" />
<meta name="twitter:creator" content="@bashebiscotti" />
```

And using [Twitter's card validator](https://cards-dev.twitter.com/validator) shows everything correctly.

![image](https://user-images.githubusercontent.com/1376749/45825677-cc2c5400-bcc0-11e8-94b7-d600780fd709.png)

Same for [Facebook's OpenGraph debugger](https://developers.facebook.com/tools/debug/).

![image](https://user-images.githubusercontent.com/1376749/45825735-eebe6d00-bcc0-11e8-96fa-19e4b4a479a4.png)

I think everything is fine with your pages.

**Comment by mmistakes** [comment]
For what it's worth Twitter uses many of the OpenGraph meta tags like title and such. That's why you might not see them all duplicated as Twitter specific meta tags. But as you can see it's picked up correctly in their validator.

**Comment by theclue** [comment]
I see...validator results looks exactly how it should.

For some reasons, when trying to share with twitter, the summary_large image won't show....

![image](https://user-images.githubusercontent.com/1724406/45826024-dae02e80-bcf3-11e8-93d3-24c942cff814.png)
