### ISSUE TITLE
Question: using remote_theme doesn't seem to be working on Github

### ISSUE THREAD

**Issue by ChristopherA** [mmistakes/so-simple-theme#321]
I've followed the docs on how to use remote_theme with this theme, and I've tried to use it as a github pages remote_theme, but my posts are not being generated, but I'm not getting any error from Github when I push updates `The page build completed successfully`

My github site is: https://github.com/BlockchainCommons/www.blockchaincommons.com 

The website is: https://www.BlockchainCommons/

The index.html is properly being generated, but when I go to *Posts* link I get a 404 error.

Has this theme been tested with remote_theme lately? I'd rather not fork.

**Comment by ChristopherA** [comment]
I figured out the problem. You must have the posts.md in the root of your repo. It is not copied with the remote_theme.

You should consider adding this to your documentation.

**Comment by mmistakes** [comment]
Installing the theme as a gem or `remote_theme` does just that... Installs the theme.

`posts.md` and any of the other files are "content". The theme doesn't copy them, that's up to you too decide what you need and how to structure.
