### ISSUE TITLE
Can't get it to work with simple fork and GH pages

### ISSUE THREAD

**Issue by reiinakano** [mmistakes/so-simple-theme#324]
Here are the steps I followed when trying to get this to build on github pages (https://github.com/reiinakano/reiinakano.github.io). I used the same steps on minimal-mistakes with success so I'm not sure why my build keeps failing.

1. Fork
2. Rename repo to reiinakano.github.io
3. I pushed an update to _config.yml changing URL to "https://reiinakano.github.io"

At this point, I would expect GH pages to build normally (as it did with minimal-mistakes), but it doesn't. I'm sure I'm just missing something simple but I can't see it from the documentation

**Comment by reiinakano** [comment]
I went with the option of building it from scratch instead of forking so I don't have this issue anymore.

**Comment by mmistakes** [comment]
I wouldn't suggest forking. It's much easier if you start a new repo, and install the theme as a `remote_theme` as [instructed in the documentation](https://github.com/mmistakes/so-simple-theme#github-pages-method).

This way you always get the latest version of the theme without having to pull in files manually.

**Comment by Lutenist** [comment]
> I wouldn't suggest forking. It's much easier if you start a new repo, and install the theme as a `remote_theme` as [instructed in the documentation](https://github.com/mmistakes/so-simple-theme#github-pages-method).
> 
> This way you always get the latest version of the theme without having to pull in files manually.

As a noob, I do not know how to start my own repo from scratch to utilise this theme. I got Minimal Mistakes to work by forking and editing the appropriate files, but was hoping I could also try out this theme!

Is there anywhere specific I should look to set up my site easily using GitHub Pages? I don't mind reading documentation, but I am not sure where to start and how to get my site going as fast as possible!

Thanks in advance :)

**Comment by mmistakes** [comment]
There are a few places in the docs where I link directly to the following starter repo which you should fork instead. The MM repo has a lot of extra stuff in it that isn't advised for forking which can make you life harder, especially if new to Jekyll, git, etc.

https://github.com/mmistakes/mm-github-pages-starter

The starter repo is configured for GitHub Pages hosted sites, setup as a remote theme, and has all of the typical pages created for you (archived, paginated home index, etc.)
