### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [mmistakes/so-simple-theme#326]
I started to use So simple theme, when I create 2 sample posts the search was working fine, After importing other posts, its not working.

URL: thedataguy.in

from google developer tools:
```Refused to execute script from 'https://thedataguy.in/assets/js/search-data.json' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.```

**Comment by BhuviTheDataGuy** [comment]
After renaming the search-data.json to  search-data.js its fixed

**Comment by mmistakes** [comment]
Duplicate of #323
