### ISSUE TITLE
problem with images showing up

### ISSUE THREAD

**Issue by thehamiltonlab** [mmistakes/so-simple-theme#330]
I'm having an issue...

After pushing to GitHub, the images are not loading/showing up. The link for them shows up, and you can click on the link and see the images...

I can't seem to figure out why this is doing this.

Any thoughts?
https://github.com/thehamiltonlab/thehamiltonlab.github.io
https://thehamiltonlab.github.io/hamilton-lab/

Thanks!
Chris

**Comment by mmistakes** [comment]
Maybe you’ve sorted things out. Just looked at your site and images show up fine for me.

**Comment by thehamiltonlab** [comment]
oh really? I can see some of the main images on the pages...but for those embedded within the text, they're just the code for the link the images (and then those show up in a gallery-like view).

**Comment by mmistakes** [comment]
Never mind I see an issue on the Hamilton lab page. You have some bad HTML. Check the `img` tag inside of the figure. You’re. Is sing a closing `>` 

Should be this instead:

```html

<figure>
	<a href="{{ site.url }}/images/Tarantula_Nocona_boot_ad.jpg"><img src="{{ site.url }}/images/Tarantula_Nocona_boot_ad.jpg" alt="image" width="150"></a>
</figure>
```

**Comment by thehamiltonlab** [comment]
Dang! Good catch. Thanks, that worked.

Appreciate it!
