### ISSUE TITLE
Security alerts

### ISSUE THREAD

**Issue by orcahmlee** [mmistakes/so-simple-theme#341]
Hi @mmistakes, 
I got two security alerts from GitHub. I've tried using `automated security fix` on GitHub but it doesn't work. Could you give me some hints about how to fix these?

![Screen Shot 2019-08-30 at 14 35 42](https://user-images.githubusercontent.com/26179752/63999734-bf51ea80-cb36-11e9-84be-0a2d0cd78e69.png)
![Screen Shot 2019-08-30 at 14 36 10](https://user-images.githubusercontent.com/26179752/63999735-bf51ea80-cb36-11e9-8f1c-57f69efad40d.png)

**Comment by mmistakes** [comment]
It's a minor thing, just bump `onchange` to 3.0 in `package.json`.

https://github.com/mmistakes/minimal-mistakes/commit/a2fdc94fb753fb76bebe842b82eeff78047285c1

This security alert has zero affect on your actual site, it's just part of a script to build the theme's JavaScript file.
