### ISSUE TITLE
gallery not working

### ISSUE THREAD

**Issue by hoch1009** [mmistakes/so-simple-theme#343]
Hi, included the gallery in the YAML Front matter and put the include at the end of the post but Github tells me there there is an error when building the page because i included a file that's a symlink or is missing in _includes.

The post can be found here: https://raw.githubusercontent.com/hoch1009/hoch1009.github.io/master/_posts/2019-09-19-southamerica.md

What am I doing wrong?

**Comment by mmistakes** [comment]
This theme doesn't support the `gallery` helper. I think you've confused it with my other theme Minimal Mistakes, which does support it.
