### ISSUE TITLE
config.yml references default.css, not default.scss

### ISSUE THREAD

**Issue by engn33r** [mmistakes/so-simple-theme#358]
## Motivation

The following line looks like a slight typo in the config.yml file, since the skins are .scss files, not .css:
`skin: "/assets/css/skins/default.css"`

## Suggestion

Even though the default will be used regardless, this should probably be:
`skin: "/assets/css/skins/default.scss"`

with an .scss extension, not .css

**Comment by alxddh** [comment]
#357

**Comment by mmistakes** [comment]
If it’s changed to .scss it’ll 404 since Jekyll is converting the files to .css 

.scss also won’t be read properly by this line in the head

https://github.com/mmistakes/so-simple-theme/blob/master/_includes/head.html#L27

**Comment by mmistakes** [comment]
In hindsight might have made more sense to abstract skin’s to names instead of paths to a file. `default`, `light`, etc.

Similar to what I do with my other theme.

https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin

**Comment by engn33r** [comment]
Ok works for me. I'm not encountering an error so I'll close this out
