### ISSUE TITLE
bundle install fails : latest version 2.1.2

### ISSUE THREAD

**Issue by sachinsshetty** [mmistakes/so-simple-theme#363]
## Environment

- So Simple version: 3.2.0
- Ruby gem or remote theme version:
- Jekyll version: 3.6
- Git repository URL: https://github.com/sachinsshetty/so-simple-theme/
- GitHub Pages hosted (if yes provide URL to site): 
- Operating system: Ubuntu 18.04

## Expected behavior

bundle install runs successfully 

## Steps to reproduce the behavior

* Error on `bundle install`
 
Output : 
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 2.0.2)

  Current Bundler version:
    bundler (2.1.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 2.0.2)' in any of the relevant sources:
  the local ruby installation

## Other 
Latest bundler stable release : 2.1.2 - https://github.com/bundler/bundler/blob/master/CHANGELOG.md

**Comment by mmistakes** [comment]
Did you try taking the advice of the error message and run `gem install bundler` first?

**Comment by sachinsshetty** [comment]
Yes.  'gem install bundler' in ubuntu 18.04 LTS installs the current stable branch 2.1.2 of bundler.  After updating version in jekyll-theme-so-simple.gemspec file . #362 ,it started working

**Comment by sachinsshetty** [comment]
fixed in #362
