### ISSUE TITLE
Problem with Newly added dropdown menu

### ISSUE THREAD

**Issue by vijaypolimeru** [mmistakes/so-simple-theme#365]
Blod Address : https://vijaypolimeru.github.io/myblog/

![image](https://user-images.githubusercontent.com/29602227/73135796-77df7400-406c-11ea-9d75-cf6057ea33a9.png)

I have added a new dropdown menu to the theme, but some how it is going behind the logo. I tried with z-index postions etc. Surprisingly, when I reduce the screen size to mobile size it is coming as expected on top of the logo, even if I go back to original screen it works as expected. However, when I refresh the browser, then the dropdown menu is going behind the site-logo. Can anyone help understand this problem

please let me know, if any further details are required

![image](https://user-images.githubusercontent.com/29602227/73135739-cc362400-406b-11ea-8efb-8deb8449f645.png)

**Comment by mmistakes** [comment]
You'll need to customize the CSS as well.
Try giving `.site-nav` the following CSS so it's relatively positioned above everything.

```css
.site-nav {
  position: relative;
  z-index: 2000;
}
```

**Comment by vijaypolimeru** [comment]
> 
> 
> You'll need to customize the CSS as well.
> Try giving `.site-nav` the following CSS so it's relatively positioned above everything.
> 
> ```css
> .site-nav {
>   position: relative;
>   z-index: 2000;
> }
> ```

Hi, I tried adding the suggested `css`, but it did not work. Please open the dropdown menu on the home page ([here](https://vijaypolimeru.github.io/randomposts/index.html)), Both the dowpdown menu and the card are from bootstrap 4.2.1 (BS4). 

Somehow, the BS4 drop-down menu is going behind the BS4 card. Could you please help me place the dropdown menu always on top.

**Comment by mmistakes** [comment]
@vijaypolimeru For CSS support reach out on Stackoverflow.
