### ISSUE TITLE
lunr in this project is not supporting Japanese (lacked script).

### ISSUE THREAD

**Issue by liqsuq** [mmistakes/so-simple-theme#366]
I'm not familiar at this module, but it will be needed upstream's tinyseg.js  for lunr supporting Japanese.
Could you add this file and modify /_includes/lunr-search-scripts.html?

https://github.com/MihaiValentin/lunr-languages/issues/42
https://github.com/MihaiValentin/lunr-languages/edit/master/tinyseg.js

**Comment by mmistakes** [comment]
If you require loading additional JavaScript consult the theme's documentation. You can use the `footer_scripts` array in _config.yml to load additional scripts of your choosing.

https://github.com/mmistakes/so-simple-theme#customizing-javascript

**Comment by liqsuq** [comment]
I tried above, but not succeeded.  Search result was not indicated.
It might need to be loaded after lunr.stemmer.support.min.js and before lunr.ja.min.js.

It doesn't matter I custom /_includes/lunr-search-scripts.html.
But don't you matter the embedded module is not working?
