### ISSUE TITLE
Build failing on GitHub pages

### ISSUE THREAD

**Issue by Hanzig** [mmistakes/so-simple-theme#371]
Hello,
I simply forked the repo, and in settings I'm getting the following. I tried it in my local and it's working fine, but fails when I try in GitHub pages. What could be wrong? Thanks a lot in advance.

Regards,
Hans

<img width="762" alt="Screenshot 2020-03-15 at 21 15 23" src="https://user-images.githubusercontent.com/1893613/76708856-d2a75a80-6702-11ea-8820-97d48bad6f65.png">

**Comment by Hanzig** [comment]
Please

**Comment by harshnisar** [comment]
@Hanzig how did you solve this?
