### ISSUE TITLE
New notices and so-simple

### ISSUE THREAD

**Issue by twhite96** [mmistakes/so-simple-theme#380]
Hi, Michael. I want to use your new notices with this theme. Most of it works well; I'm using these notices on a paid Jekyll theme and that works great. 

Whenever I try to build my site, there is a SASS compilation error:
`Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/skins/dark.scss': Undefined mixin 'notice'. on line 190`

This is because this theme doesn't recognize the new notices as there are no mixins for the current version of your notices. The old notices worked fine but I really, really like the new ones.

I've gone into the gem and deleted the offending code but when rebuilt, as you know, that code is regenerated. My question is, how can I build either a SASS mixin to get this to work or do you have any other suggestions?

Thank you.

**Comment by mmistakes** [comment]
Check the Sass documentation on how to create mixins.

https://sass-lang.com/documentation/at-rules/mixin

**Comment by twhite96** [comment]
Not really working. Can you show me an example? I'm not sure how to go about this. I tried writing my own mixin, etc. When I remove the offending code from the gem it runs fine locally but of course it doesn't in production or the Docker container I usually run Jekyll in.
