### ISSUE TITLE
Problem with the Newly added dropdown menu

### ISSUE THREAD

**Issue by vijaypolimeru** [mmistakes/so-simple-theme#382]
## Summary
The newly added bootstrap 4.2.1 (BS4) dropdown menu is going behind the BS4 card.

## Motivation
The motivation behind adding a  drop-down menu is to strategically organize the content, 

## Drawbacks

I have added a (BS4) dropdown menu to the so-simple theme. However, it is not working as excepted, I raised a similar issue [here ](https://github.com/mmistakes/so-simple-theme/issues/365#issue-555227401) some time back, the developer Mr. Mmistakes suggested to add the following to css in `.site-nav`, 

```
.site-nav {
  position: relative;
  z-index: 2000;
}
```
I did that, but it did not resolved the probelm. The exact problem I am facing can be viewed [here](https://vijaypolimeru.github.io/randomposts/index.html), upon clicking, the newly added BS4 dropdown menu is somehow it is going behind the BS4 card. I tried with z-index, postions etc. Surprisingly, when I reduce the screen size to mobile size it is coming as expected (i.e. dropdown is opening above the card), even if I go back to original screen it works as expected. However, when I refresh the browser, then the dropdown menu is going behind the card. Can anyone help me resolve this problem

**Comment by mmistakes** [comment]
Closing as this isn't the appropriate place to ask for CSS help. Issues on this repo are for bug reports. If you're customizing the CSS and need help with that [Stackoverflow forums](https://stackoverflow.com/questions/tagged/css) are a better place for that.
