### ISSUE TITLE
Changes to kramdown break Mathjax rendering. (Easy Fix)

### ISSUE THREAD

**Issue by knuthingmuch** [mmistakes/so-simple-theme#388]
The incompatibility between kramdown's output for latex snippets and the default input for MathJax3 [has been resolved](https://github.com/gettalong/kramdown/issues/626). 

This means that the workaround code to get `<script>` enclosed math to work with MathJax3 is no longer needed and should be removed eventually.

For **_includes/scripts.html**: [diff.txt](https://github.com/mmistakes/so-simple-theme/files/5070136/diff.txt)

**Comment by mmistakes** [comment]
Feel free to submit a pull request with the fix.
