### ISSUE TITLE
Improve support for syntax highlighting `linenos=table` option

### ISSUE THREAD

**Issue by mchelen** [mmistakes/so-simple-theme#91]
The `{% highlight %}` tag for syntax highlighting works fine:
![syntax highlighting post default](https://cloud.githubusercontent.com/assets/30691/4276312/343f0d44-3d04-11e4-8d1c-5dc1bfe582f4.png)

Line numbers can be added using `linenos`:
![syntax highlighting post linenos](https://cloud.githubusercontent.com/assets/30691/4276313/344c6890-3d04-11e4-8707-2dd1390ed826.png)

With `linenos` however the line numbers are selected when trying to copy the code. This can be fixed by using `linenos=table` but this is not handled in the theme styling:
![syntax highlighting post linenos table](https://cloud.githubusercontent.com/assets/30691/4276314/34696ddc-3d04-11e4-9da5-5828cbf80823.png)

Reference: http://pygments.org/docs/formatters/

**Comment by mmistakes** [comment]
This has been fixed and will be landing in #265 once merged.

**Comment by mmistakes** [comment]
3.0.1 has been released with this fix.
